language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: sesion6travisheroku
  on: master
  skip_cleanup: true
  api_key:
    secure: HzNc3vlfHnFjSD++fWq9qFsdJxaUu4VZg/bZpnkkMB+ZxdONxcoM0yUF028434WFyUMot/jA7vtUWcBpTyII2+2yaoZkaaOU5nJb4BYmnSSQ/jVazqmxH9yQ4PiFdSlv+LDmeAlGUamkuAqRlCrHvBGxvup8eoBYl51/68eVUT3ewOXzEsS+dPzUF5cgdoE+wy2M27qj0pEeOxcXqIuUzpC2kfhnHviJsUtRHiRAOZevRuw5vW6NrssCQ1OtqkMr49JspkGj2j/EDtZ2R3Z/+qrb496KmaWz2O2fgj1AOYuLmDmzunqXFOd2cyg6QI4GP+Ae9yxX8gSptqbmdzmbqFeYKcgZEXususkYvGcyOW16OqcLiIPZyFIYI7CjK+dVqN6jUkY6iJhvKdMsohJnLpAztLNfn2XW+P8yBNJMUWPvTyvFqxNEAChptq8a7X4BSpiHPVq6BX4+p01+RuCRHPa4/9UN1yzsAsD9HW68pNPx4/+44MBTLbseRrnJVCM5WaxtjmYEm5TXHY1ewhKeGnNCNSnEnkIBx6jSlw9J/mOayfVzhDXrbVOJsBvpzYOOMxGwbzEvfIxihfI4c6C3wxSupOGWagrA7QP/zqB4+nUQQmRmfTPg13rvRQlDh9sY8Fv/VWToNJIr1adzZ0mm4S/TCmBRlVIOxQn4v5m8+/0=

