language: php
php:
- 7.2
services:
- mysql
before_script:
- composer install
script: "./vendor/bin/phpunit ./tests"
deploy:
  provider: heroku
  api_key:
    secure: N6Re9yoF2UwQB7eu0D7RW6p4rMKtzYk4Lg/4xmlDyzCbDxzdxin5IsiPuHmpwNmi/hBNpviwn4pYsxhqcUhTnC6AXby/WhD3tiVRuci0Cq+8ijtCbgpq3zM6wWvIzXcQkAr5m0/f58h8E2K6yadYiaSEj59s2flQFc5aLELRxmW0gZ2rtrnWzzJdbNtN4o7dvx55LhIBthnId+KhzM35zGhuR/qxXxIRhwLbQrAeLkrvcvud94PJxfG09KF2HfjZ6xnI1ggdA33pOkd/NOsXFZKmSAT4XPTtwTWc2//G12fJLmujGsuRDqCpe6+SxjatZIYVxLljrt9blWBgEqzED68dnJE5h6Z9PssY3oUJHHkfwCPiEN8BoG2KkziEkapCgRi/riI6/GbzwX+tF3NrIvak7ERxTHGqlSk50+k14yg7dttYa1IPTFGaInVk0nEWHfwS7gTeZ773e/sGLvwC5RrIPLea8cLNqILojFvX+wwjR1TeVFajH/AzgJ3YWkWrGn8dNxQVLGaoLh8WWx68Iw3y8rZ+6YkzbokfkonpNBgnJPKEgM3XSpKwzJ7qqLn4sTBDK8xEObItlJSy/5WhxJa6uguOjEji4jEmHrVkZnz4MGuaMleZfNtiS59UEfj7EYdth1I3MTF4yGBX+DILhm8V37CuBzabVikLeTwvgFo=
  app: sesion6travisheroku
  on:
    repo: organizacion-sesion-3-Manuel-Arnau/sesion6-travis-heroku
  skip_cleanup: 'true'
