language: php
php:
- 7.2
services:
- mysql
before_script:
- composer install
script: "./vendor/bin/phpunit ./tests"
deploy:
  provider: heroku
  app: sesion6travisheroku
  on: master
  api_key:
    secure: Cph3COhaBxYexXmPekZN10oj0F7V64eFXUui8+gOGSq89uEWqrKJaZ4Ed9u6mgD+KQneC65WSnAxZyQTL6pWXurndfa5BjD0KBK2KnohtNK87HML4e+WBB9za7bU+/g07zyoluX4msRZh00om1aFZ6zKgwZZ871P11brmHJ/iSePBMaCN/I2vo6fUSBJuOlObKjklotIZvjmnZq2zOflH2WJcgyY6QFPCiggZcWvVjyb3HmpMzrLhFV7COnnV45WcYKgYdkLfQnAOvmu8Rq0bhadzkU4f+mqtqILlTcZdvhjSj8rIXj1jtn8Q3THbqXVMkoME9CzIX4bKQS17x6w0ydq5w+gn58tc3yVt9MrY/z4dDuY1pHHIkJm1gZk4GVSekIIzN/tUGWTjhRqp1pqIFVJQje/V9PBEVfE5l5LLzdZYJ0tuHMQ0X5ZLjfiRErZiT9B+hsYgyjCoqDDyJ3qyvZe8vyPqaOPjn7pDfFckZKgA+HIzA7w/abiYHvB/Lmo7ri8+UU9EIUuF5TTLhH2L4LJlMzdUk9nNmamMw2+CcHbl1HeNj9pHwg5pM7TK0cQ976prfh/umJOW6+589TcYCE5AyZf8cUTKmp/J35qJSCh66r9xrs5cpWPl0Mr8Dw2gJmKhr/PQMG0TUt9wJPq1GByCtlhG/0SZgmDaySij3I=
