language: php
php:
- 7.2
services:
- mysql
before_script:
- composer install
script: "./vendor/bin/phpunit ./tests"
deploy:
  provider: heroku
  app: sesion6travisheroku
  on: master
  skip_cleanup: true
  api_key:
    secure: gfBrimAgCRfut6So/nWWPdHpLqUYS8KcazemKdbJOT8DjhdMGwhIMsokX9uq9on2dqisLAnN0cd0gvCqn87IOB+1g7bIIYI6pjUWd1jyUlA1YaL8eCnJkrcRvVzU2cZgQx59LTEmU/05nDOkm1Mk4POO6LQ+TF1HuA3Ym0yq8Xrd64AkTTx0C4U1jKsDXnegbTW0pC8lz8T/ZLFKtOZJkCe7Pbzu6PD5avLjQ+/Dt4sO0fL7Z0E6uR2Azh6HLs6sthyQS7jkQTOFSgXvsi6RR1UlFYj5lJewymg+mrKSgRfUr4efLaxMun3L3pTKGPiRmk/AKP8716Gefdk2fnFNGkHHVBhPQ8fQ4K6XUNQ+5kvJotgRvbsaRsaVr7AjLOl6OKliP17lFMvbwWDuTapL0rGHzP12v+hIFV9FM3a03oCNe4r9T3pBFutbRkpcFLs94QGFPJoQyrdXGkaZegfy/MPmVZREwURGxaW3ozpJwBKClzlqopCX8Wq7W7UNPCw1503DsWaHeIWHfc961Vmao3bhsI6Huq7zTPXgjBSP4JvFTzUd0xrQBU1J0uQnJUFKpE/l98S7u0+g55R+YpQD7niPEKHgzQnZliMDFap8IWMfb8P5XtkFMFjcMmreFF3LYeRMcyyhRvBxbXCwwLvP33q0fAADEey8P9tBOQQWUdU=
