language: php
php:
- 7.2
services:
- mysql
before_script:
- composer install
script: "./vendor/bin/phpunit ./tests"
deploy:
  provider: heroku
  app: sesion6travisheroku2
  on: master
  skip_cleanup: true
  api_key:
    secure: FWETBz8uZcMdU1j0pTlhO0J76b3urm697FJF5E6udwZEeYyBEmswA1vlFWrzqr0ByInwQr+VGp3XZXt1kdmulnCHfw7BhjBh670q4yZZDCqQoyjlT1LvM0Mhuv9taOonVTTUTXZaFVWb1ZVjw4swYZDS6P3djrykgRLas0DO4ZjFl+r/qu4/OWS6jLQjIRymQN1UrzWEYHQurzhU6OvWDuxVoGr14FFD/JtwkuKFhg4as+gIRvZ+CwhlBdc5V8YKMxFAM+7fSTuqiYBIntUIix1Ce3r2I8AhZCXCcZECl+Hy6DboVq1GyxkDlt3bYjBNiBUd7v9ZmPHOZQp6Tg+O+jEJuWilh9tJACZsFiS+mu4oSut/ZFQISM82UxLeaFKXfA1CuxRx9TEbouG/RXwyLovC4uyWozpPosgaIW19LeRVf+G2gmH8vx/xWTbpLEgh1vj+Agq9AOoKOj8QEO64gHUS9aEQCysqrTj7EFHaTuGWvdo4Dy4QtGs2D7YKZ7IxrAfvUGPQeXTktXnl6qnAJT6X+KGEffSKQNUv6fTiogQ7jW8xhrbiOioK91uUF8hWbiK6Qk277tE8RRtOAgyOOsAafuRBX36uDetjEvqWKkfrdsGkksE4eP+dbps9KXUrGQoaZD7LuPoBS+/7IiEiLgiV1gbzaL7/E9Fwt0hCdf4=
