language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: sesion6travisheroku2
  on: master
  skip_cleanup: true
  api_key:
    secure: QTwWdyBgiYAP4py+ujPQZ7bd6XUReMdCOBZL5yDZSog2lOl48aVnphjaNwk5I35KoZnmzdmp1jYYro0tPhYBCWwev3zwhvGJbVp5bwd4EU13lYFUgJotDPARdHZuKKRAdaT18omTXg+pjzh/KnOc0AaH0qzoOiB41xZJ4YXD9B2wEsP68bZ4PRI7VlJmQRb4IKWQyd5YrfQEosXwwZBXuN4og2Pycxa7eA9AJVM5pUqatPOLW/jLmKqPHYXKQv+IIVbWw+ZG0eeRzT7t6XrP2nBAdYtsRzFiG8BarZKZv2xyXfAB3wtBKnJNQMT35Fy/8vrW3wPg9uyGIM2jdhbEAbs2A3dym5diT4JEC91nYdbJEyMpTnY+oWgPRLg0FeuFn3qF2tZh73M4jdosN8js6A0hbCvrwfy8XsyYd9aVsTdoHjcdB5Qf+0LYk9D1mt8A9pjdUx+lsIt4BYO+jbpYLXiFqBLMmbJlrv5dkItLJT+ZChR3hkDGJtMl5+Zo+bgZ9s0RUdT4kqfrjVcNIWFo84EZ+XwjhJwO9OjjUBJUPkEQAx+VnFwfm6z3OEisAYqA8bH7s/Eb/L+EJGx8wz7JoyHzSyfxk00LT7X1bKbke6QGq1JzPkUJ2YIdvuq2BU8Z3IvD91m4fg3wCfUNrqFRTKbGAOrp0yGxOslAiU4HTKQ=
