language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: sesion6travisheroku
  on: master
  skip_cleanup: true
  api_key:
    secure: cZiCY7xmh2mO5T0U5ihrOkpEo91rYx/l/3PjEWiJ6kRga6xqrmI8xMQlY9M4XxEdG/DTfcQmpDiMaSDnoRrZT0eMYiOaqOhXTHtBELb9rYzGPapgsgI0RPA1UpFFsx3vawDAdJUuqjutn3GZcfGO+rkCOWETGi+7TnQ4umQU3jP5s4POZ9fA6ZP9T6ixXRDdO+HaNONPNJfZK8pbTPQnmS0Y6WcGU2kwIco1VBAQY40skA5gWxNsmbGW140ZEpKAIlrxpfOGDHlINENSe5n+piAQLA9ZcSYhDxrJL06ZekSUlsifFDoHEzKFmvUg5f5W0DtH7rIZ7K1AUM6Qn/OjibV/kN6MQzLSfqPCRABHRcljhxgQiFBFeFpPI2t2hinRuT9rN0fcwl0RZT5hz1tyzjpD7SnIpwUAK22NbCaZHDr4miSLBQ4KKTujbBulnQ/lpQLH3xF3QXsvxtkaa4TjYM7nu9QReH4D3Pylh2F6+EEhIR64zKrIXAXiy0O/mJ6+EgqbFLGQSVQi5maUn0kh9vf0jEIR683ZZjML781iOP6WEn+hFMT1t7/8cbqRGMV1iHo7J5A70Krn1WuaIODPQYODDWsWwA/VsRu02P2eY9Q9M+jLFkUoYEzs9h3973hCeQc21V+ExVTnBb2oh8uZ+R/E2Qbo3C+8U7geKZyMlwE=
